[project]
name = "siteplan"
version = "0.1.0"
requires-python = ">=3.12"

[tool.black]
target-version = ['py312']
line-length = 88

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
