[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "siteplan"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = []

[tool.black]
target-version = ['py38']

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203"]
